name: directus-iles-template

services:
  database:
    container_name: database
    image: postgis/postgis:16-master
    platform: linux/amd64
    volumes:
      - ./cms/data/database:/var/lib/postgresql/data
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-U',
          '${DB_USER}',
          '-d',
          '${DB_DATABASE}',
          '-h',
          'localhost',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    container_name: cache
    image: redis:6
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cms:
    container_name: directus
    image: directus/directus:11.13.4
    env_file:
      - ./cms/.env
    ports:
      - '${DIRECTUS_PORT}:8055'
    restart: always
    networks:
      - internal
    volumes:
      - ./cms/uploads:/directus/uploads
      - ./cms/extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_AUTO_PURGE: ${CACHE_AUTO_PURGE}
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}

      PUBLIC_URL: ${PUBLIC_URL}

      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}

      REFRESH_TOKEN_COOKIE_SECURE: ${REFRESH_TOKEN_COOKIE_SECURE}
      REFRESH_TOKEN_COOKIE_SAME_SITE: ${REFRESH_TOKEN_COOKIE_SAME_SITE}
      REFRESH_TOKEN_DOMAIN: ${REFRESH_TOKEN_COOKIE_DOMAIN}

      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      SESSION_COOKIE_SAME_SITE: ${SESSION_COOKIE_SAME_SITE}
      SESSION_COOKIE_DOMAIN: ${SESSION_COOKIE_DOMAIN}

      EXTENSIONS_PATH: ${EXTENSIONS_PATH}
      EXTENSIONS_AUTO_RELOAD: ${EXTENSIONS_AUTO_RELOAD}
      EXTENSIONS_ROLLDOWN: ${EXTENSIONS_ROLLDOWN}

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: ${CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC}

      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}

  frontend:
    container_name: iles
    profiles: ['prod']
    build: ./frontend
    working_dir: /app
    ports:
      - '3000:3000'
      - '5173:5173'
    env_file:
      - ./frontend/.env
    restart: always
    networks:
      - internal

  nginx:
    container_name: reverse-proxy
    profiles: ['prod']
    image: nginx:latest
    depends_on:
      - cms
      - frontend
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://frontend:3000 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge
